export const ADD_POST_REQUEST = "ADD_POST_REQUEST"
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS"
export const ADD_POST_FAILED = "ADD_POST_FAILED"

export const GET_POST_COUNT_REQUEST = "GET_POST_COUNT_REQUEST"
export const GET_POST_COUNT_SUCCESS = "GET_POST_COUNT_SUCCESS"
export const GET_POST_COUNT_FAILED = "GET_POST_COUNT_FAILED"

export const GET_POST_REQUEST = "GET_POST_REQUEST"
export const GET_POST_SUCCESS = "GET_POST_SUCCESS"
export const GET_POST_FAILED = "GET_POST_FAILED"

export const GET_MY_POST_REQUEST = "GET_MY_POST_REQUEST"
export const GET_MY_POST_SUCCESS = "GET_MY_POST_SUCCESS"
export const GET_MY_POST_FAILED = "GET_MY_POST_FAILED"
export const DELETE_POST="DELETE_POST"
export const FIND_POST_SUCCESS="FIND_POST_SUCCESS"
export const UPDATE_POST_SUCESS="UPDATE_POST_SUCESS"
export const GET_OTHER_POST_SUCCESS="GET_OTHER_POST_SUCCESS"
